version: 2
formats:
  - htmlzip
  - pdf
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"
python:
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt
mkdocs:
  configuration: mkdocs.yml
