version: '3.8'
services:
    pytest:
        build:
            context: .
            dockerfile: Dockerfile
        privileged: true
        volumes:
            - ./:/var/project
        command: ./runtests.sh
