# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Version tag

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Version tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
    - name: Is last commit bump version
      id: version_number
      continue-on-error: true
      run: |
        OUTPUT=$(git show -q | grep "Bump version from" | awk '{print $6}') &&
        echo "OUTPUT=$OUTPUT" >> $GITHUB_OUTPUT
    - name: Git tag & push
      if: steps.version_number.outputs.OUTPUT != ''
      run: |
        git tag ${{ steps.version_number.outputs.OUTPUT }}
        git push --tags
