# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Version bump

on:
  workflow_dispatch:
    inputs:
      versionPart:
        description: 'Version bump part'
        required: true
        default: patch
        type: choice
        options:
        - patch
        - minor
        - major

jobs:
  deploy:
    name: Version bump on release branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4.3.0
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipx
    - name: Setup git config
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git checkout -b release
    - name: Bumpversion
      run: |
        pipx run --spec git+https://github.com/bulv1ne/poetry-bumpversion poetry-bumpversion ${{ github.event.inputs.versionPart }}
    - name: Git push
      run: |
        git push origin release
    - name: Create Pull Request
      uses: actions/github-script@v6
      with:
        script: |
          const { repo, owner } = context.repo;
          const result = await github.rest.pulls.create({
            title: 'Release version',
            owner,
            repo,
            head: 'release',
            base: 'main',
            body: [
              'This PR is auto-generated by',
              '[actions/github-script](https://github.com/actions/github-script).'
            ].join('\n')
          });
